<?php
/**
 * Created by PhpStorm.
 * User: Junior
 * Date: 15/03/2017
 * Time: 21:37
 */

namespace App\Validation;

class FuncionarioValidation extends Validation
{

    protected static $rules = [
        'novo_funcionario' => 'required|boolean',
        'nome_completo' => 'required|max:191',
        'nome_mae' => 'required|max:191',
        'nome_pai' => 'required|max:191',
        'id_estado_civil' => 'required|exists:estado_civil,id',
        'data_nascimento' => 'required|date_format:d/m/Y',
        'nacionalidade' => 'required|max:191',
        'naturalidade' => 'required|max:191',
        'id_grau_instrucao' => 'required|exists:grau_instrucao,id',
        'id_grupo_sanguineo' => 'nullable|exists:grupo_sanguineo,id',
        'id_raca' => 'nullable|exists:raca,id',
        'id_sexo' => 'required|exists:sexo,id',
        'telefone' => 'required|max:20',
        'email' => 'nullable|email',
        'estrangeiro' => 'required|boolean',
        'id_condicao_estrangeiro' => 'sometimes|exists:grau_instrucao,id',
        'data_chegada_estrangeiro' => 'nullable|date_format:d/m/Y',
        'numero_processo_mte' => 'nullable|max:191',
        'numero_rne' => 'nullable|max:191',
        'data_expedicao_rne' => 'nullable|date_format:d/m/Y',
        'data_validade_rne' => 'nullable|date_format:d/m/Y',
        'validade_carteira_trabalho' => 'nullable|date_format:d/m/Y',
        'casado_estrangeiro' => 'nullable|boolean',
        'filho_estrangeiro' => 'nullable|boolean',
        'cep' => 'required|size:9',
        'id_uf' => 'required|exists:uf,id',
        'cidade' => 'required|max:191',
        'bairro' => 'required|max:191',
        'endereco' => 'required|max:191',
        'numero' => 'required|numeric',
        'complemento' => 'nullable|max:191',
        'residente_exterior' => 'nullable|boolean',
        'residencia_propria' => 'nullable|boolean',
        'imovel_fgts' => 'nullable|boolean',
        'cpf' => 'required|size:14',
        'rg' => 'required|max:14',
        'orgao_expedidor_rg' => 'required|max:191',
        'data_emissao_rg' => 'required|date_format:d/m/Y',
        'pis' => 'required|size:14',
        'data_cadastro_pis' => 'nullable|date_format:d/m/Y',
        'ctps' =>'required|max:191',
        'data_emissao_ctps' => 'required|date_format:d/m/Y',
        'id_uf_ctps'=>'required|exists:uf,id',
        'titulo_eleitor'=>'nullable|max:191',
        'zona_secao_eleitoral'=>'nullable|max:191',
        'cnh'=>'nullable|max:191',
        'categoria_cnh'=>'nullable|max:191',
        'vencimento_cnh' => 'nullable|date_format:d/m/Y',
        'carteira_reservista'=>'nullable|max:191',
        'categoria_carteira_reservista'=>'nullable|max:191',
        'contrato.cargo'=>'required|max:191',
        'contrato.funcao'=>'required|max:191',
        'contrato.departamento'=>'required|max:191',
        'contrato.id_categoria_contrato_trabalho'=>'required|exists:categoria_contrato_trabalho,id',
        'contrato.vinculo_empregaticio'=>'required|exists:vinculo_empregaticio,id',
        'contrato.salario'=>'required|numeric',
        'contrato.data_admissao'=> 'required|date_format:d/m/Y',
        'contrato.vale_transporte'=>'required|boolean',
        'contrato.valor_vale_transporte'=>'nullable|numeric',
        'contrato.desconto_assistencia_medica'=>'nullable|numeric',
        'contrato.desconta_vale_transporte'=>'nullale|boolean',
        'contrato.primeiro_emprego'=>'nullable|boolean',
        'contrato.professor'=>'nullable|boolean',
        'contrato.experiencia'=>'nullable|boolean',
        'contrato.qtde_dias_experiencia'=>'nullable|numeric',
        'contrato.qtde_dias_prorrogacao_experiencia'=>'nullable|numeric',
        'contrato.sindicalizado'=>'required|boolean',
        'contrato.sindicato'=>'sometimes|max:191',
        'contrato.competencia_sindicato'=>'nullable|date_format:d/m/Y',
        'contrato.dsr'=>'required|numeric',
        'dia_trabalho.*.hora1'=>'nullable|size:4',
        'dia_trabalho.*.hora2'=>'nullable|size:4',
        'dia_trabalho.*.hora3'=>'nullable|size:4',
        'dia_trabalho.*.hora4'=>'nullable|size:4',
        'dia_trabalho.*.dia'=>'required|numeric',
        'dependentes.*.nome'=>'required|max:191',
        'dependentes.*.id_tipo_dependencia'=>'required|exists:tipo_dependencia,id',
        'dependentes.*.cpf'=>'nullable|size:14',
        'dependentes.*.rg'=>'nullable|max:191',
        'dependentes.*.orgao_expedidor_rg'=>'nullable|max:191',
        'dependentes.*.data_nascimento'=>'required|date_format:d/m/Y',
        'dependentes.*.local_nascimento'=>'required|max:191',
        'dependentes.*.matricula'=>'nullable|max:191',
        'dependentes.*.cartorio'=>'nullable|max:191',
        'dependentes.*.numero_cartorio'=>'nullable|max:191',
        'dependentes.*.numero_livro'=>'nullable|max:191',
        'dependentes.*.numero_folha'=>'nullable|max:191',
        'dependentes.*.numero_dnv'=>'nullable|max:191'

    ];

    protected static $niceNames = [
        'novo_funcionario' => 'Tipo de Cadastro',
        'nome_completo' => 'Nome completo do funcionário',
        'nome_mae' => 'Nome completo da mãe ',
        'nome_pai' => 'Nome completo do pai',
        'id_estado_civil' => 'Estado civil',
        'data_nascimento' => 'Data de nascimento',
        'nacionalidade' => 'Nacionalidade',
        'naturalidade' => 'Naturalidade',
        'id_grau_instrucao' => 'Grau de instrução',
        'id_grupo_sanguineo' => 'Grupo sanguíneo',
        'id_raca' => 'Raça/Cor',
        'id_sexo' => 'Sexo',
        'telefone' => 'Telefone do funcionário',
        'email' => 'E-mail do funcionário',
        'estrangeiro' => 'É estrangeiro?',
        'id_condicao_estrangeiro' => 'Condição',
        'data_chegada_estrangeiro' => 'Data de chegada',
        'numero_processo_mte' => 'Número do processo MTE',
        'numero_rne' => 'Número do RNE',
        'data_expedicao_rne' => 'Data de expedição do RNE',
        'data_validade_rne' => 'Data de validade do RNE',
        'validade_carteira_trabalho' => 'Data de validade da CTPS',
        'casado_estrangeiro' => 'Casado(a) com brasileiro(a)',
        'filho_estrangeiro' => 'Filho(s) com brasileiro(a)',
        'cep' => 'CEP',
        'id_uf' => 'Estado',
        'cidade' => 'Cidade',
        'bairro' => 'Bairro',
        'endereco' => 'Endereço',
        'numero' => 'Número',
        'complemento' => 'Complemento',
        'residente_exterior' => 'Residente/domiciliado no exterior',
        'residencia_propria' => 'Residência própria',
        'imovel_fgts' => 'Imóvel adquirido com recursos do FGTS',
        'cpf' => 'CPF',
        'rg' => 'RG',
        'orgao_expedidor_rg' => 'Órgão expedidor do RG com UF',
        'data_emissao_rg' => 'Data de emissão RG',
        'pis' => 'PIS',
        'data_cadastro_pis' => 'Data de cadastro PIS',
        'ctps' =>'Carteira de trabalho (CTPS)',
        'data_emissao_ctps' => 'Data de emissão CTPS',
        'id_uf_ctps'=>'UF de emissão CTPS',
        'titulo_eleitor'=>'Número do título eleitoral',
        'zona_secao_eleitoral'=>'Zona e seção eleitoral',
        'cnh'=>'Número da CNH',
        'categoria_cnh'=>'Categoria da CNH',
        'vencimento_cnh' => 'Vencimento da CNH',
        'carteira_reservista'=>'Número de reservista',
        'categoria_carteira_reservista'=>'Categoria de reservista',
        'contrato.cargo'=>'Cargo',
        'contrato.funcao'=>'Função',
        'contrato.departamento'=>'Departamento',
        'contrato.id_categoria_contrato_trabalho'=>'Categoria',
        'contrato.vinculo_empregaticio'=>'Vínculo empregatício',
        'contrato.salario'=>'Salário (R$)',
        'contrato.data_admissao'=> 'Data de admissão',
        'contrato.vale_transporte'=>'Recebe vale transporte?',
        'contrato.valor_vale_transporte'=>'Valor de vale tranporte (R$)',
        'contrato.desconto_assistencia_medica'=>'Desconto de assistência médica (R$)',
        'contrato.desconta_vale_transporte'=>'Desejo descontar o Vale Transporte do funcionário (6%)',
        'contrato.primeiro_emprego'=>'Primeiro emprego',
        'contrato.professor'=>'Professor',
        'contrato.experiencia'=>'Desejo emitir o contrato de experiência',
        'contrato.qtde_dias_experiencia'=>'Quantidade de dias',
        'contrato.qtde_dias_prorrogacao_experiencia'=>'Quantidade de dias de prorrogação',
        'contrato.sindicalizado'=>'Sindicato',
        'contrato.sindicato'=>'Nome do sindicato',
        'contrato.competencia_sindicato'=>'Data da última contribuição',
        'contrato.dsr'=>'D.S.R',
        'dia_trabalho.*.hora1'=>'Entrada - 1° TURNO',
        'dia_trabalho.*.hora2'=>'Saída - 1° TURNO',
        'dia_trabalho.*.hora3'=>'Entrada - 2° TURNO',
        'dia_trabalho.*.hora4'=>'Saída - 2° TURNO',
        'dia_trabalho.*.dia'=>'Dia',
        'dependentes.*.nome'=>'Nome completo',
        'dependentes.*.id_tipo_dependencia'=>'Tipo de dependência',
        'dependentes.*.cpf'=>'CPF',
        'dependentes.*.rg'=>'RG',
        'dependentes.*.orgao_expedidor_rg'=>'Órgão Expedidor do RG',
        'dependentes.*.data_nascimento'=>'Data de Nascimento',
        'dependentes.*.local_nascimento'=>'Local de nascimento',
        'dependentes.*.matricula'=>'Matrícula da certidão de nascimento',
        'dependentes.*.cartorio'=>'Nome do cartório',
        'dependentes.*.numero_cartorio'=>'Número de registro do cartório',
        'dependentes.*.numero_livro'=>'Número do livro',
        'dependentes.*.numero_folha'=>'Número da folha',
        'dependentes.*.numero_dnv'=>'Número da D.N.V'
    ];


}
