<!-- Cálculo de mensalidade -->
@include('dashboard.components.mensalidade.simulate')

<div class="col-xs-12">
    <h3>Resumo da sua solicitação</h3>
    <hr>
</div>
<div class="col-sm-6" >
    <p><strong><span style="font-size: 10.0pt; line-height: 115%; font-family: 'Arial',sans-serif; color: black;">CONTRATO DE PRESTA&Ccedil;&Atilde;O DE SERVI&Ccedil;OS CONT&Aacute;BEIS</span></strong></p>
    <p span style="font-size: 10.0pt; line-height: 115%; font-family: 'Arial',sans-serif; color: black;">CONTRATADA: WEBCONT SERVICOS ADMINISTRATIVOS LTDA, inscrita no CNPJ 28.398.863/0001-88.</p>
    <p span style="font-size: 10.0pt; line-height: 115%; font-family: 'Arial',sans-serif; color: black;">CONTRATANTE: xxxxxxxxxxxxx.</p>
    <ol>
        <li style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;"> - <strong>DO OBJETO</strong></span></li>
    </ol>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">O objeto do presente consiste na presta&ccedil;&atilde;o pela CONTRATADA aa CONTRATANTE, dos seguintes servi&ccedil;os profissionais:</span></p>
    <p style="text-align: justify; text-indent: -18.0pt; line-height: normal; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">1.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- &Aacute;REA FISCAL:</span></p>
    <p style="text-align: justify; text-indent: -36.0pt; line-height: normal; margin: 0cm 0cm .0001pt 36.0pt;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">1.1.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Orienta&ccedil;&atilde;o e controle da aplica&ccedil;&atilde;o dos dispositivos legais vigentes, sejam federais, estaduais ou municipais;</span></p>
    <p style="text-align: justify; text-indent: -36.0pt; line-height: normal; margin: 0cm 0cm .0001pt 36.0pt;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">1.1.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Escritura&ccedil;&atilde;o dos registros fiscais do IPI, ICMS, ISS e elabora&ccedil;&atilde;o das guias de informa&ccedil;&atilde;o e de recolhimento dos tributos devidos;</span></p>
    <p style="text-align: justify; text-indent: -36.0pt; line-height: normal; margin: 0cm 0cm .0001pt 36.0pt;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">1.1.3&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Atendimento das demais exig&ecirc;ncias previstas em atos normativos, bem como de eventuais procedimentos de fiscaliza&ccedil;&atilde;o tribut&aacute;ria.</span></p>
    <p style="text-align: justify; text-indent: -18.0pt; line-height: normal; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">1.2&nbsp;&nbsp;- &Aacute;REA DO IMPOSTO DE RENDA PESSOA JUR&Iacute;DICA:</span></p>
    <p style="text-align: justify; text-indent: -36.0pt; line-height: normal; margin: 0cm 0cm .0001pt 36.0pt;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">1.2.1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Orienta&ccedil;&atilde;o e controle de aplica&ccedil;&atilde;o dos dispositivos legais vigentes;</span></p>
    <p style="text-align: justify; text-indent: -36.0pt; line-height: normal; margin: 0cm 0cm .0001pt 36.0pt;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">1.2.2&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Elabora&ccedil;&atilde;o da declara&ccedil;&atilde;o anual de rendimentos e documentos correlatos;</span></p>
    <p style="text-align: justify; text-indent: -36.0pt; line-height: normal; margin: 0cm 0cm .0001pt 36.0pt;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">1.2.3&nbsp;&nbsp;&nbsp;- Atendimento das demais exig&ecirc;ncias previstas em atos normativos, bem como de eventuais procedimentos de fiscaliza&ccedil;&atilde;o.</span></p>
    <p style="text-align: justify; text-indent: -18.0pt; line-height: normal; margin: 0cm 0cm .0001pt 18.0pt;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">1.3&nbsp;&nbsp;- &Aacute;REA TRABALHISTA E PREVIDENCI&Aacute;RIA:</span></p>
    <p style="text-align: justify; text-indent: -36.0pt; line-height: normal; margin: 0cm 0cm .0001pt 36.0pt;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">1.3.1&nbsp;&nbsp;&nbsp;- Orienta&ccedil;&atilde;o e controle da aplica&ccedil;&atilde;o dos preceitos da Consolida&ccedil;&atilde;o das Leis do Trabalho, bem como aqueles atinentes &agrave; Previd&ecirc;ncia Social, "PIS", "FGTS" e outros aplic&aacute;veis &agrave;s rela&ccedil;&otilde;es de emprego mantidas pela CONTRATANTE;</span></p>
    <p style="text-align: justify; text-indent: -36.0pt; line-height: normal; margin: 0cm 0cm .0001pt 36.0pt;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">1.3.2&nbsp;&nbsp;&nbsp;&nbsp;- Manuten&ccedil;&atilde;o dos Registros de Empregados e servi&ccedil;os correlatos;</span></p>
    <p style="text-align: justify; text-indent: -36.0pt; line-height: normal; margin: 0cm 0cm .0001pt 36.0pt;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">1.3.3&nbsp;&nbsp;&nbsp;&nbsp;- Elabora&ccedil;&atilde;o da Folha de Pagamento dos empregados e de Pr&oacute;-Labore, bem como das guias de recolhimento dos encargos sociais e tributos afins;</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">1.3.4 - Atendimento das demais exig&ecirc;ncias previstas na legisla&ccedil;&atilde;o, bem como de eventuais procedimentos de fiscaliza&ccedil;&atilde;o.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">1.4 - O Usu&aacute;rio acessar&aacute; seu perfil e informa&ccedil;&otilde;es da contabilidade de sua empresa atrav&eacute;s de email e senha cadastrados e compromete-se a n&atilde;o informar a terceiros esses dados, responsabilizando-se integralmente pelo uso que deles seja feito. O usu&aacute;rio ser&aacute; o &uacute;nico respons&aacute;vel pelas opera&ccedil;&otilde;es efetuadas em sua conta, uma vez que o acesso &agrave; mesma s&oacute; ser&aacute; poss&iacute;vel mediante a utiliza&ccedil;&atilde;o de e-mail e senha, cujo conhecimento &eacute; exclusivo do usu&aacute;rio.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">&nbsp;</span></p>
    <ol start="2">
        <li style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;"> - <strong>DAS CONDI&Ccedil;&Otilde;ES DE EXECU&Ccedil;&Atilde;O DOS SERVI&Ccedil;OS</strong></span></li>
    </ol>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">Os servi&ccedil;os ser&atilde;o executados nas depend&ecirc;ncias da CONTRATADA, em obedi&ecirc;ncia &agrave;s seguintes condi&ccedil;&otilde;es:</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">2.1. - A documenta&ccedil;&atilde;o indispens&aacute;vel para o desempenho dos servi&ccedil;os arrolados na cl&aacute;usula 1 ser&aacute; fornecida pela CONTRATANTE, consistindo, basicamente, em:</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">2.1.1 &ndash; Notas Fiscais de compra (entradas) e de venda (sa&iacute;das), bem como comunica&ccedil;&atilde;o de eventual cancelamento das mesmas;</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">2.1.2 - Controle de frequ&ecirc;ncia dos empregados e eventual comunica&ccedil;&atilde;o para concess&atilde;o de f&eacute;rias, admiss&atilde;o ou rescis&atilde;o contratual, bem como corre&ccedil;&otilde;es salariais espont&acirc;neas.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">2.2. - A documenta&ccedil;&atilde;o dever&aacute; ser enviada pela CONTRATANTE de forma completa e em boa ordem nos seguintes prazos:</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">2.2.1 - At&eacute; 5 (cinco) dias ap&oacute;s o encerramento do m&ecirc;s, os documentos relacionados nos itens 2.1.1, acima;</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">2.2.2 - Mensalmente, os documentos mencionados no item 2.1.2 acima, no 2&deg; (primeiro) dia &uacute;til do m&ecirc;s seguinte;</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">2.2.3 - No m&iacute;nimo 48 (quarenta e oito) horas antes a comunica&ccedil;&atilde;o para da&ccedil;&atilde;o de aviso de f&eacute;rias e aviso pr&eacute;vio de rescis&atilde;o contratual de empregados acompanhada do Registro de Empregados.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">2.3 - A CONTRATADA compromete-se a cumprir todos os prazos estabelecidos na legisla&ccedil;&atilde;o de reg&ecirc;ncia quanto aos servi&ccedil;os contratados, especificando-se, por&eacute;m, os prazos abaixo:</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">2.3.1 - A entrega das guias de recolhimento de tributos e encargos trabalhistas &agrave; CONTRATANTE se far&aacute; com anteced&ecirc;ncia de 2 (dois) dias do vencimento da obriga&ccedil;&atilde;o.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">2.3.2 - A entrega da Folha de Pagamento, recibos de pagamento salarial, de f&eacute;rias e demais obriga&ccedil;&otilde;es trabalhistas far-se-&aacute; at&eacute; 72 (setenta e duas) horas ap&oacute;s o recebimento dos documentos mencionados no item 2.1.2.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">2.4. - A remessa de documentos entre os CONTRATANTEs dever&aacute; ser feita sempre pelo site atrav&eacute;s de processo espec&iacute;fico ou chamado.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">&nbsp;</span></p>
    <ol start="3">
        <li style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;"> <strong>DOS DEVERES DA CONTRATADA</strong></span></li>
    </ol>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">3.1 - A CONTRATADA desempenhar&aacute; os servi&ccedil;os enumerados na cl&aacute;usula 1 com todo zelo, dilig&ecirc;ncia e honestidade, observada a legisla&ccedil;&atilde;o vigente, resguardando os interesses da CONTRATANTE, sem preju&iacute;zo da dignidade e independ&ecirc;ncia profissionais, sujeitando-se, ainda, &agrave;s normas do C&oacute;digo de &Eacute;tica Profissional do Contabilista, aprovado pela Resolu&ccedil;&atilde;o N&deg; 803/96 do Conselho Federal de Contabilidade.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">3.2 - N&atilde;o se incluem na responsabilidade assumida pela CONTRATADA os juros e a corre&ccedil;&atilde;o monet&aacute;ria de qualquer natureza, visto que n&atilde;o se tratam de apenamento pela mora, mas sim recomposi&ccedil;&atilde;o e remunera&ccedil;&atilde;o do valor n&atilde;o recolhido.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">3.3 - A CONTRATADA n&atilde;o assume nenhuma responsabilidade pelas consequ&ecirc;ncias de informa&ccedil;&otilde;es, declara&ccedil;&otilde;es ou documenta&ccedil;&atilde;o inid&ocirc;neas ou incompletas que lhe forem apresentadas, bem como por omiss&otilde;es pr&oacute;prias da CONTRATANTE ou decorrentes do desrespeito &agrave; orienta&ccedil;&atilde;o prestada.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">&nbsp;</span></p>
    <ol start="4">
        <li style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;"> - <strong>DOS DEVERES DO CONTRATANTE HONOR&Aacute;RIOS E REEMBOLSOS</strong></span></li>
    </ol>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">4.1. - Obriga-se a CONTRATANTE a fornecer &agrave; CONTRATADA todos os dados, documentos e informa&ccedil;&otilde;es que se fa&ccedil;am necess&aacute;rios ao bom desempenho dos servi&ccedil;os ora contratados, em tempo h&aacute;bil, nenhuma responsabilidade cabendo &agrave; segunda acaso recebidos intempestivamente.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">4.2. - Responsabilizar-se pela veracidade de todas informa&ccedil;&otilde;es enviadas pelo site.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">4.3. - Respeitar as Cl&aacute;usulas deste TERMO ONLINE, bem como os valores relacionados aos servi&ccedil;os contratados.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">4.2.1. - &nbsp;Caso o presente envolva a recupera&ccedil;&atilde;o de servi&ccedil;os n&atilde;o realizados - atrasados - a mensalidade adicional ser&aacute; integralmente devida desde o primeiro m&ecirc;s de atualiza&ccedil;&atilde;o.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">4.2.2 - Os honor&aacute;rios pagos ap&oacute;s a data aven&ccedil;ada no item 4.2. acarretar&atilde;o aa CONTRATANTE o acr&eacute;scimo de multa de 2% (dois por cento), sem preju&iacute;zo de juros morat&oacute;rios de 1% (um por cento) ao m&ecirc;s ou fra&ccedil;&atilde;o, acrescidos de corre&ccedil;&atilde;o monet&aacute;ria equivalente ao IGP-M.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">4.2.3 &ndash; Os honor&aacute;rios ser&atilde;o reajustados anualmente e automaticamente, considerando-se como m&ecirc;s de ajuste outubro de cada ano.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">4.2.4 - O valor dos honor&aacute;rios previstos no item 4.2 foi estabelecido segundo o n&uacute;mero de s&oacute;cios que retiram o pr&oacute;-labore, o n&uacute;mero de funcion&aacute;rios e o n&uacute;mero de notas fiscais, ficando certo que se os mesmos forem superiores aos par&acirc;metros mencionados, passar&aacute; a vigorar nova mensalidade. </span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">4.4. - Os servi&ccedil;os solicitados pela CONTRATANTE n&atilde;o especificados na cl&aacute;usula 1 ser&atilde;o cobrados pela CONTRATADA em apartado, como extraordin&aacute;rios, segundo valor espec&iacute;fico constante de or&ccedil;amento previamente aprovado pela primeira, englobando nessa previs&atilde;o toda e qualquer inova&ccedil;&atilde;o da legisla&ccedil;&atilde;o relativamente ao regime tribut&aacute;rio, trabalhista ou previdenci&aacute;rio.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">4.4.1 - S&atilde;o considerados servi&ccedil;os extraordin&aacute;rios ou para-cont&aacute;beis, exemplificativamente: 1) Altera&ccedil;&atilde;o contratual; 2) Abertura de empresa ou filial; 3) Certid&otilde;es negativas do INSS, FGTS, Federais, ICMS e ISS; 4) Certid&atilde;o negativa de fal&ecirc;ncias ou protestos; 5) Homologa&ccedil;&atilde;o junto &agrave; DRT; 6) Autentica&ccedil;&atilde;o/Registro de Livros; 7) Encaderna&ccedil;&atilde;o de livros; 8) Declara&ccedil;&atilde;o de ajuste do imposto de renda pessoa f&iacute;sica; 9) Preenchimento de fichas cadastrais/IBGE; 10) Elabora&ccedil;&atilde;o de Balancete e Balan&ccedil;o; 11) Emiss&atilde;o de faturamento.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">&nbsp;</span></p>
    <ol start="5">
        <li style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;"> - <strong>DA VIG&Ecirc;NCIA E RESCIS&Atilde;O</strong></span></li>
    </ol>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">5.1 - Este Contrato &eacute; v&aacute;lido pelo per&iacute;odo de 30 (trinta) dias, sendo prorrogado automaticamente por iguais per&iacute;odos caso n&atilde;o haja manifesta&ccedil;&atilde;o em contr&aacute;rio por nenhuma das Partes.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">5.2 - Ocorrendo a transfer&ecirc;ncia dos servi&ccedil;os para outra Empresa Cont&aacute;bil, a CONTRATANTE dever&aacute; informar &agrave; CONTRATADA, por escrito, seu nome, endere&ccedil;o, nome do respons&aacute;vel e n&uacute;mero da inscri&ccedil;&atilde;o junto ao Conselho Regional de Contabilidade, sem o que n&atilde;o ser&aacute; poss&iacute;vel &agrave; CONTRATADA cumprir as formalidades &eacute;tico-profissionais, inclusive a transmiss&atilde;o de dados e informa&ccedil;&otilde;es necess&aacute;rias &agrave; continuidade dos servi&ccedil;os, em rela&ccedil;&atilde;o &agrave;s quais, diante da eventual in&eacute;rcia da CONTRATANTE, estar&aacute; desobrigada de cumprimento.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">5.2.1 - Entre os dados e informa&ccedil;&otilde;es a serem fornecidos n&atilde;o se incluem detalhes t&eacute;cnicos dos sistemas de inform&aacute;tica da CONTRATADA, os quais s&atilde;o de sua exclusiva propriedade.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">5.3 &ndash; O n&atilde;o pagamento da parcela faculta &agrave; CONTRATADA suspender imediatamente a execu&ccedil;&atilde;o dos servi&ccedil;os ora pactuados, bem como considerar rescindido o presente, independentemente de notifica&ccedil;&atilde;o judicial ou extrajudicial.</span></p>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">5.4 &ndash; O presente contrato entra em vigor na data do aceite da proposta e ter&aacute; vig&ecirc;ncia por tempo indeterminado, podendo ser rescindido em qualquer &eacute;poca, por qualquer uma das partes, mediante Aviso Pr&eacute;vio de 30 (trinta) dias, por meio eletr&ocirc;nico.</span></p>
    <ol start="6">
        <li style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;"> - <strong>DO FORO</strong></span></li>
    </ol>
    <p style="margin-bottom: .0001pt; text-align: justify; line-height: normal;"><span style="font-size: 10.0pt; font-family: 'Arial',sans-serif; color: black;">Fica eleito o Foro da Cidade de Blumenau, com expressa ren&uacute;ncia a qualquer outro, por mais privilegiado que seja, para dirimir as quest&otilde;es oriundas da interpreta&ccedil;&atilde;o e execu&ccedil;&atilde;o do presente contrato.</span></p>
</div>
<div class="col-sm-6 summary">

    <div class="description">Mensalidade: <span class="price" id="mensalidade">R$69,90</span></div>
    <ul class="items">
        <li>Quantidade de funcionários: <span id="qtde-funcionarios">0</span></li>
        <li>Quantidade de documentos fiscais recebidos e emitidos mensalmente: <span id="qtde-documentos-fiscais">0</span></li>
    </ul>

</div>
<div class="col-xs-12 text-right">
    <hr>
    <button class="btn btn-default back"><i class="fa fa-angle-left"></i> Voltar - CNAEs</button>
    <button type="submit" class="btn btn-success"><span class="fa fa-check"></span> De acordo (Finalizar)
    </button>
</div>